export const projectsData: any = [
  {
    uid: "xWDQUkBZ6qchztTuagNt",
    headerMark: null,
    hasAllowListing: false,
    supply: 5000,
    hasTimedDrop: false,
    metadataCid: null,
    hasWhiteLabel: false,
    tokenURI: null,
    productionContractAddress: null,
    imageExtension: ".png",
    network: "ethereum",
    allowlistDropTime: null,
    website: "",
    isPaidPremium: false,
    mintPrice: 0.01,
    testnetTxnHash: null,
    erc20PaymentOptionsTestnet: [],
    earlyMintIncentiveCap: 100,
    hasSupplyCap: true,
    plan: "free",
    payables: [
      { amount: 100, address: "0x4dcd23e1ca295adcc72223d4d5f6df3d8f0fb6a2" },
    ],
    mintingOpen: true,
    hasEarlyMintWalletIncentive: false,
    adminAddresses: ["0x4dcd23e1ca295adcc72223d4d5f6df3d8f0fb6a2"],
    hasWalletMax: false,
    walletMax: 3,
    enforceRoyalties: true,
    hasEarlyMintIncentive: false,
    maxMintPerTxn: 2,
    earlyMintIncentivePrice: 0,
    hasMintFee: true,
    contractURI: null,
    name: "My Mintplex Project",
    whitelistedAddresses: [],
    preRevealMetadataCid: null,
    onlyOwnerMinting: false,
    contractMetaFile: null,
    erc20PaymentOptionsMainnet: [],
    tokenSymbol: "MINTPLEX",
    sellerFeeBasisPoints: 0,
    contractFile: null,
    createdAt: { _seconds: 1672072877, _nanoseconds: 361000000 },
    canAcceptERC20: true,
    publicDropTime: null,
    contractType: "ERC-721A",
    contractVersion: 2,
    earlyMintWalletIncentiveCap: 1,
    metadataExtension: ".json",
    earlyMintWalletIncentivePrice: 0,
    preRevealImageCid: null,
    testnetContractAddress: null,
    productionTxnHash: null,
  },
];

export const project: any = {
  uid: "xWDQUkBZ6qchztTuagNt",
  contractMetaFile: null,
  contractType: "ERC-721A",
  supply: 5000,
  allowlistDropTime: null,
  hasAllowListing: false,
  plan: "free",
  payables: [
    { address: "0x4dcd23e1ca295adcc72223d4d5f6df3d8f0fb6a2", amount: 100 },
  ],
  onlyOwnerMinting: false,
  erc20PaymentOptionsMainnet: [],
  network: "ethereum",
  tokenSymbol: "MINTPLEX",
  adminAddresses: ["0x4dcd23e1ca295adcc72223d4d5f6df3d8f0fb6a2"],
  hasEarlyMintWalletIncentive: false,
  contractURI: null,
  testnetTxnHash: null,
  erc20PaymentOptionsTestnet: [],
  hasWalletMax: false,
  productionContractAddress: null,
  headerMark: null,
  contractVersion: 2,
  isPaidPremium: false,
  earlyMintIncentivePrice: 0,
  hasTimedDrop: false,
  earlyMintWalletIncentiveCap: 1,
  hasMintFee: true,
  canAcceptERC20: true,
  hasEarlyMintIncentive: false,
  hasSupplyCap: true,
  enforceRoyalties: true,
  mintingOpen: true,
  productionTxnHash: null,
  earlyMintWalletIncentivePrice: 0,
  publicDropTime: null,
  testnetContractAddress: null,
  metadataCid: null,
  tokenURI: null,
  createdAt: {
    _seconds: 1672072877,
    _nanoseconds: 361000000,
  },
  metadataExtension: ".json",
  whitelistedAddresses: [],
  preRevealMetadataCid: null,
  hasWhiteLabel: false,
  website: "",
  contractFile: null,
  preRevealImageCid: null,
  maxMintPerTxn: 2,
  mintPrice: 0.01,
  walletMax: 3,
  earlyMintIncentiveCap: 100,
  sellerFeeBasisPoints: 0,
  imageExtension: ".png",
  name: "My Mintplex Project",
};
